In [1]:
import torch

In [2]:
x = torch.tensor([0.5, 0.75], requires_grad = True)
v = x[0] * x[1]
v

tensor(0.3750, grad_fn=<MulBackward0>)

In [28]:
a = torch.tensor([1.0, 2.0, 3.0], requires_grad = True)
b, c, d = a.unbind()

In [14]:
b

tensor(1., grad_fn=<UnbindBackward0>)

In [15]:
c

tensor(2., grad_fn=<UnbindBackward0>)

In [29]:
d

tensor(3., grad_fn=<UnbindBackward0>)

In [17]:
#b.backward()

In [18]:
a.grad

In [19]:
c.backward()

In [20]:
a.grad

tensor([0., 1., 0.])

In [46]:
x = torch.tensor([1.0], requires_grad = True)
y = torch.tensor([4.0], requires_grad = False)

In [50]:
z = x * y
z

tensor([4.], grad_fn=<MulBackward0>)

In [51]:
#z.requires_grad = True

In [52]:
pi = torch.tensor([3.14], requires_grad = False)

In [53]:
zpi = z * pi
zpi

tensor([12.5600], grad_fn=<MulBackward0>)

In [54]:
zpi.backward()

In [55]:
z.grad

C:\Users\Priangshu Paul\AppData\Local\Temp\ipykernel_28152\4110045842.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\build\aten\src\ATen/core/TensorBody.h:494.)
  z.grad


In [56]:
pi.grad

In [57]:
x.grad

tensor([12.5600])

In [58]:
y.grad