In [1]:
import torch

In [2]:
# Input Data
i = torch.tensor([.05, .1])

In [3]:
# Weight and Bias Initialization

# Layer 1
w_1 = torch.tensor([.15, .20, .25, .30], requires_grad = True)
b1 = torch.tensor([.35], requires_grad = True)

# Layer 2
w_2 = torch.tensor([.40, .45, .50, .55], requires_grad = True)
b2 = torch.tensor([.60], requires_grad = True)  

In [4]:
# Actual Output
y1 = torch.tensor([.01])
y2 = torch.tensor([.99])

In [5]:
# Forward Pass
# Layer 1
z1 = i[0] * w_1[0] + i[1] * w_1[2] + b1
z2 = i[0] * w_1[1] + i[1] * w_1[3] + b1

In [6]:
# Forward Pass
# Passing through activation function
a1 = torch.sigmoid(z1)
a2 = torch.sigmoid(z2)

In [7]:
# Forward Pass
# Output Layer
z3 = a1 * w_2[0] + a2 * w_2[1] + b2
z4 = a1 * w_2[2] + a2 * w_2[3] + b2

In [8]:
# Forward Pass
# Passing through activation function
y1_pred = torch.sigmoid(z3)
y2_pred = torch.sigmoid(z4)

In [9]:
# Error Calculation
E01 = ((y1 - y1_pred) ** 2) / 2
E02 = ((y2 - y2_pred) ** 2) / 2

In [10]:
# Total Error
E = E01 + E02

In [11]:
# Backward Pass
E.backward()

In [12]:
w_2.grad

tensor([ 0.0823,  0.0826, -0.0226, -0.0227])

In [13]:
b2.grad

tensor([0.1004])

In [14]:
w_1.grad

tensor([0.0004, 0.0005, 0.0009, 0.0010])

In [15]:
b1.grad

tensor([0.0187])